### ISSUE TITLE
Content Element doesn't shows up

### ISSUE THREAD

**Issue by hilbaONE** [Hauer-Heinrich/hh_openstreetmap#2]
I've got the newest version of your nice extension. Sadly the content element "OpenStreetMap" has disappear from the "create new content element" > "Typical page content" tab. So I can't create a new element!

**Comment by Teisi** [comment]
Which TYPO3 version do you use?

And have you included the PageTs typoscript? (Backend -> RootPage -> Page settings -> Resources)

**Comment by hilbaONE** [comment]
11.5.22
This "include" solved the problem. Thanks a lot for support
