### ISSUE TITLE
It's not possible to create markers

### ISSUE THREAD

**Issue by jacques2017** [Hauer-Heinrich/hh_openstreetmap#3]
Hi,
I use TYPO3 12 in composer-mode and hh_openstreetmap v0.3.0
It is not possible to create markers in the conten-element. In the  TYPO3-protokoll if find this:
![grafik](https://github.com/Hauer-Heinrich/hh_openstreetmap/assets/26480486/6542a435-3661-4525-8101-7a93733a0707)

**Comment by Teisi** [comment]
Same as #4, will be fixed soon...
