### ISSUE TITLE
hh_openstreetmap 0.3.0: Typo3 12.4.9 can not use extension icon 

### ISSUE THREAD

**Issue by pwilladt** [Hauer-Heinrich/hh_openstreetmap#4]
Problem source:
the extension icon (ext_icon.png) lies direct within the extensions' root directory
(and the extension is configured to use it from there).
Apparently, with Typo3 12.4.9, it is required that the extension lies within a public
accessible directory, e.g. Resources/Public/Icons.
Consequences: 
- Icon missing in extension listing (minor)
- Trying to edit a already created plugin configuration results in a 503 error.
Suggestion:
Move the icon to another folder:
(`mv ext_icon.png Resources/Public/Icons/`)
correct path to icon:
(change `Configuration/TCA/tx_hh_openstreetmap_marker.php` in line 22 to contain 
`'iconfile' => 'EXT:hh_openstreetmap/Resources/Public/Icons/ext_icon.png',`
instead of the previous value)

**Comment by Teisi** [comment]
Thank you! And sorry for the late response - will be fixed soon.
